# Generated by Django 5.0.6 on 2024-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='profile_pictures/'),
        ),
    ]
